#!/usr/bin/env node

var ArgumentParser = require('argparse').ArgumentParser;

var ActionList = require('./lib/actionlist');
var ActionBuild = require('./lib/actionbuild');

var parser = new ArgumentParser({
  version: '0.0.1',
  addHelp:true,
  description: 'Build script for FTB Server Docker containers'
});

var commandParsers = parser.addSubparsers({
	title:'command',
	dest:'command_name'
});

var listArgs = commandParsers.addParser('list', {addHelp:true});
listArgs.register('action', 'list', ActionList);
listArgs.addArgument(
	'list',
	{
		action: 'list',
		help: 'List modpacks filtered by minecraft version',
		nargs: 0
	});

var buildArgs = commandParsers.addParser('build', {addHelp:true});
buildArgs.register('action', 'build', ActionBuild);
buildArgs.addArgument(
	['modpack'],
	{
		action: 'build',
		help: 'Modpack name',
		nargs: '*'
	});

var args = parser.parseArgs();
//console.log(args);
/*
try {
  var doc = yaml.safeLoad(fs.readFileSync('packs.yml', 'utf8'));
  console.log(doc['direwolf20'])
} catch (e) {
  console.log(e);
}*/