FROM feedthebeast/ftbbase

ARG DOWNLOAD_URL={{ download_url }}
ARG ZIP_NAME={{ name }}.zip
ARG DYNMAP_URL

COPY setup.sh ./
RUN /bin/bash setup.sh && \
    rm setup.sh

WORKDIR /home/minecraft/mcmyadmin
