FROM ftbbase

ARG DOWNLOAD_URL={{ download_url }}
ARG ZIP_NAME={{ name }}.zip

WORKDIR /home/minecraft/mcmyadmin/Minecraft
COPY gen_server_properties.sh ./

RUN	wget -O $ZIP_NAME $DOWNLOAD_URL && \
	unzip $ZIP_NAME && \
	rm $ZIP_NAME

RUN mv *.jar ftbserver.jar && \
	/bin/sh ./FTBInstall.sh && \
	echo "eula=true" > eula.txt

RUN /bin/sh ./gen_server_properties.sh && \
	rm gen_server_properties.sh

WORKDIR /home/minecraft/mcmyadmin